package branch;

import java.util.List;

import qtUtils.branchingReturnC;
import qtUtils.myEdge;
import abstractClasses.Certificate;
import abstractClasses.SearchResult;
import controller.Controller;
import edu.uci.ics.jung.graph.util.Pair;

public class clusterP4<V> extends clusterBranch<V> 
{

	public clusterP4(Controller<V> controller) {
		super(controller);
		
	}
	
	@Override
	public branchingReturnC<V> branchingRules(branchingReturnC<V> s, SearchResult<V> searchResult)
	{
		Certificate<V> certificate = searchResult.getCertificate();
		
		//find structures
		this.findStructures(s, searchResult);
		
		
		//check if p4 is present
		if (certificate.getFlag() == -2)
		{
			List<V> lexResult = certificate.getVertices();
			double oldPercent = s.getPercent();
			
			//RULES GENERATED BY EDITOR
			int ruleCount = 5;
			//3 additions and 0 deletions
			if (!s.getChanges().contains(new myEdge<V>(new Pair<V>(lexResult.get(0), lexResult.get(2)), false, directed))
				&& !s.getChanges().contains(new myEdge<V>(new Pair<V>(lexResult.get(0), lexResult.get(3)), false, directed))
				&& !s.getChanges().contains(new myEdge<V>(new Pair<V>(lexResult.get(1), lexResult.get(3)), false, directed)))
			{
				if (output)
				{
					//change progress percent
					s.setPercent(oldPercent / ruleCount);
				}
				addResult(s, lexResult.get(0), lexResult.get(2));
				addResult(s, lexResult.get(0), lexResult.get(3));
				addResult(s, lexResult.get(1), lexResult.get(3));
				controller.branch(s);
				revert(s, 3);
				if (output)
				{
					//revert percent
					s.setPercent(oldPercent);
				}
			}
			else
				if (output)
					controller.setGlobalPercent(controller.getGlobalPercent() + oldPercent / ruleCount);

			//1 additions and 1 deletions
			if (!s.getChanges().contains(new myEdge<V>(new Pair<V>(lexResult.get(0), lexResult.get(2)), false, directed))
				&& !s.getChanges().contains(new myEdge<V>(new Pair<V>(lexResult.get(2), lexResult.get(3)), true, directed)))
			{
				if (output)
				{
					//change progress percent
					s.setPercent(oldPercent / ruleCount);
				}
				addResult(s, lexResult.get(0), lexResult.get(2));
				deleteResult(s, lexResult.get(2), lexResult.get(3));
				controller.branch(s);
				revert(s, 2);
				if (output)
				{
					//revert percent
					s.setPercent(oldPercent);
				}
			}
			else
				if (output)
					controller.setGlobalPercent(controller.getGlobalPercent() + oldPercent / ruleCount);

			//1 additions and 1 deletions
			if (!s.getChanges().contains(new myEdge<V>(new Pair<V>(lexResult.get(0), lexResult.get(1)), true, directed))
				&& !s.getChanges().contains(new myEdge<V>(new Pair<V>(lexResult.get(1), lexResult.get(3)), false, directed)))
			{
				if (output)
				{
					//change progress percent
					s.setPercent(oldPercent / ruleCount);
				}
				deleteResult(s, lexResult.get(0), lexResult.get(1));
				addResult(s, lexResult.get(1), lexResult.get(3));
				controller.branch(s);
				revert(s, 2);
				if (output)
				{
					//revert percent
					s.setPercent(oldPercent);
				}
			}
			else
				if (output)
					controller.setGlobalPercent(controller.getGlobalPercent() + oldPercent / ruleCount);

			//0 additions and 1 deletions
			if (!s.getChanges().contains(new myEdge<V>(new Pair<V>(lexResult.get(1), lexResult.get(2)), true, directed)))
			{
				if (output)
				{
					//change progress percent
					s.setPercent(oldPercent / ruleCount);
				}
				deleteResult(s, lexResult.get(1), lexResult.get(2));
				controller.branch(s);
				revert(s, 1);
				if (output)
				{
					//revert percent
					s.setPercent(oldPercent);
				}
			}
			else
				if (output)
					controller.setGlobalPercent(controller.getGlobalPercent() + oldPercent / ruleCount);

			//0 additions and 2 deletions
			if (!s.getChanges().contains(new myEdge<V>(new Pair<V>(lexResult.get(0), lexResult.get(1)), true, directed))
				&& !s.getChanges().contains(new myEdge<V>(new Pair<V>(lexResult.get(2), lexResult.get(3)), true, directed)))
			{
				if (output)
				{
					//change progress percent
					s.setPercent(oldPercent / ruleCount);
				}
				deleteResult(s, lexResult.get(0), lexResult.get(1));
				deleteResult(s, lexResult.get(2), lexResult.get(3));
				controller.branch(s);
				revert(s, 2);
				if (output)
				{
					//revert percent
					s.setPercent(oldPercent);
				}
			}
			else
				if (output)
					controller.setGlobalPercent(controller.getGlobalPercent() + oldPercent / ruleCount);
			
		}
	}
	

}
